### ISSUE TITLE
Test - Choosing Neither X11 Nor Wayland

### ISSUE THREAD

**Issue by Elliria** [Elliria/autokey-fork#5]
### Do you use X11 or Wayland?

- [ ] Wayland
- [ ] X11

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Enhancement

### Which AutoKey GUI did you use?

None

### Can you briefly describe the issue?

Testing the issue template to see what happens if the user doesn't pick one of the two choices in the X11/Wayland question.

### Can the issue be reproduced?

None

**Comment by Elliria** [comment]
Hey there, @josephj11. How's this? It's a checkbox instead of a drop-down, it's at the top of the questions, and if they don't answer it, we'll know they didn't.

**Comment by josephj11** [comment]
Great! Is it possible to add a note below the checkbox that says - If you're using Wayland, AutoKey won't work. Currently, t requires X11.

**Comment by Elliria** [comment]
It does when you're filling out the report. Try opening an issue and see how it looks now and let me know if there's anything I should change.

As you know, the above report is the end result after the user has already filled it out, so we don't get to see the red emojis or the warning. This should also be what we see in email, although I didn't receive an email of my own bug report, oddly enough. Should I add the warning to the Wayland choice as well so that it shows up in the final report, too?

**Comment by Elliria** [comment]
Also, this was a test of me deliberately not choosing X11 or Wayland. I'll do another test choosing Wayland.

**Comment by josephj11** [comment]
It would be good to add it to the Wayland choice, so if we get mad, we can tell them RTFM or I told you so. JK LOL

**Comment by josephj11** [comment]
Any chance YAML supports radio buttons? The form let me check both Wayland and X11.

**Comment by Elliria** [comment]
YAML supports radio buttons, but GitHub doesn't, so I went back to using a drop-down and created a new issue (issue #8)  with it. You'll want to try starting an issue, too, to see what you think of how it's presented. I also put several notes into issue #8 with explanations and a possible alternate solution.
